[project]
name = "comfyui-dapao-tool"
description = "🍭 大炮-Qwen3VL ComfyUI 自定义节点集合，集成了阿里云 Qwen 团队开发的 Qwen3-VL 多模态大语言模型系列。"
version = "1.0.6"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/paolaoshi/ComfyUI-Qwen3VL-DP"

[tool.comfy]
PublisherId = "paolaoshi"
DisplayName = "大炮-Qwen3VL"
Icon = ""
Banner = ""

