[project]
name = "comfyui-qwen3vl-dp-en-videochat"
description = "🍭 ComfyUI custom node pack integrating Alibaba Qwen team's Qwen3-VL multimodal LLMs, with English UI + Video Chat support."
version = "1.0.9"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/SmokingDormouse/ComfyUI-Qwen3VL-DP-EN-VideoChat"

[tool.comfy]
PublisherId = "SmokingDormouse"
DisplayName = "Qwen3VL-DP (EN + VideoChat)"
Icon = ""
Banner = ""